global:
  scrape_interval: 15s
  external_labels:
    container: ${HOSTNAME}

scrape_configs:
  - job_name: app
    basic_auth:
      username: prometheus
      password: "12345678"
    static_configs:
      - targets:
          - localhost:8080

remote_write:
  - url: https://prometheus-prod-10-prod-us-central-0.grafana.net/api/prom/push
    basic_auth:
      username: 566683
      password: eyJrIjoiMTBhYzI0OTRkODhiODM5NTNhNmM4NzgzNjE0Y2UxMjliNDVjYmNkMyIsIm4iOiJ0ZXN0IiwiaWQiOjcwNzE1MH0=
